---
- name: 'symlink ~/Dropbox/gnupg to ~/.gnupg'
  file:
    src: '~/Dropbox/gnupg'
    dest: '~/.gnupg'
    state: 'link'
    force: 'yes'

- name: 'symlink ~/Dropbox/projects to ~/projects'
  file:
    src: '~/Dropbox/projects'
    dest: '~/projects'
    state: 'link'
    force: 'yes'

- name: 'symlink ~/Dropbox/projects/password-store to ~/.password-store'
  file:
    src: '~/Dropbox/projects/password-store'
    dest: '~/.password-store'
    state: 'link'
    force: 'yes'

- name: 'symlink ~/Dropbox/projects/tmuxinator-templates to ~/.tmuxinator'
  file:
    src: '~/Dropbox/projects/tmuxinator-templates'
    dest: '~/.tmuxinator'
    state: 'link'
    force: 'yes'
