---
- name: 'Put the ~/.ssh/id_rsa-github.pub file in place'
  copy:
    src: 'id_rsa-github.pub'
    dest: '~/.ssh/id_rsa-github.pub'
    mode: '0644'
    force: 'yes'

- name: 'Put the ~/.ssh/id_rsa-github file in place'
  copy:
    content: "{{ id_rsa_github_private_key }}"
    dest: '~/.ssh/id_rsa-github'
    mode: '0400'
    force: 'yes'
