---
- name: 'Put the ~/.ssh/id_rsa-work.pub file in place'
  copy:
    src: 'id_rsa-work.pub'
    dest: '~/.ssh/id_rsa-work.pub'
    mode: '0644'

- name: 'Put the ~/.ssh/id_rsa-work file in place'
  copy:
    content: "{{ id_rsa_work_private_key }}"
    dest: '~/.ssh/id_rsa-work'
    mode: '0400'
