# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
HOSTNAME = "dotfile-test-vm"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "trusty64"

  # Hostname is relevant to which puppet manifest gets applied
  config.vm.hostname = HOSTNAME

  # Set the virtualbox name to be the hostname
  config.vm.define HOSTNAME do |t|
  end

end
