---
- shell: 'ls -1 ~/.bash'
  register: contents
  changed_when: False

- name: 'Ensure that the .bash directory contains nothing else'
  file:
    name: "~/.bash/{{ item }}"
    state: 'absent'
  with_items: contents.stdout_lines
  when: item not in bash_managed_files
