---
- shell: 'ls -1 ~/.functions'
  register: contents
  changed_when: False

- name: 'Ensure that the .functions directory contains nothing else'
  file:
    name: "~/.functions/{{ item }}"
    state: 'absent'
  with_items: contents.stdout_lines
  when: item not in functions_managed_files
