---
- name: 'Ensure we can connect to this host'
  ping:

- name: 'Add extra homebrew repositories'
  homebrew_tap:
    tap: "{{ item }}"
    state: 'present'
  with_items: 'homebrew_taps'

- name: 'Install homebrew packages'
  homebrew:
    name: "{{ item }}"
    state: 'latest'
  with_items: 'homebrew_packages'

- name: 'brew cleanup'
  shell: '/usr/local/bin/brew cleanup'
  register: command_result
  changed_when: 'command_result.stdout'
