#!/bin/bash

host=$1
default_r=49
default_g=66
default_b=84
defaulttitle="localhost"
LUMIN_THRESHOLD=75
STARTING_FACTOR=0.48


if [ "$2" ]; then
  exec ssh $*
fi


trap cleanup 1 2 3 6


# Cleanup after ourselves
function cleanup() {
  get_iterm_color_string $default_r $default_g $default_b
  defaultcolor=$__
  set_iterm_color "${defaultcolor}"
  set_iterm_title "${defaulttitle}"
}


function get_r() {
  local mhash=`echo "$1" | md5`
  local rr=$((0x${mhash:0:2}))
  __=$rr
}


function get_g() {
  local mhash=`echo "$1" | md5`
  local gg=$((0x${mhash:2:2}))
  __=$gg
}


function get_b() {
  local mhash=`echo "$1" | md5`
  local bb=$((0x${mhash:4:2}))
  __=$bb
}


function get_iterm_color_string() {
  local rr=$1
  local gg=$2
  local bb=$3
  # set background color to {$(($R*65535/255)), $(($G*65535/255)), $(($B*65535/255))}
  local retColor=$(($rr*65535/255))
  retColor="${retColor}, $(($gg*65535/255))"
  retColor="${retColor}, $(($bb*65535/255))"
  __=$retColor
}


# Calculate the perceived luminance
# Nothing too fancy here, idea from: http://stackoverflow.com/a/596243/1101070
function calc_perceived_luminance() {
  local rr=$1
  local gg=$2
  local bb=$3
  local res=`echo "0.2126*${rr} + 0.7152*${gg} + 0.0722*${bb}" | bc`
  # Round it down to the nearest integer
  local res=`echo "$res / 1" | bc`
  ___=$res
}


# Darken the color, if need be
function darken_rgb() {
  local rr=$1
  local gg=$2
  local bb=$3
  local factor=$STARTING_FACTOR
  calc_perceived_luminance $rr $gg $bb
  local lumin=$___
  local ctr=0
  while [ $lumin -gt $LUMIN_THRESHOLD ]; do
    # Darken each component by a factor
    rr=`echo "($rr - ($factor * $rr))/1" | bc`
    gg=`echo "($gg - ($factor * $gg))/1" | bc`
    bb=`echo "($bb - ($factor * $bb))/1" | bc`
    calc_perceived_luminance $rr $gg $bb
    lumin=$___
    factor=`echo "$factor + 0.01" | bc`
    ctr=$(($ctr+1))
  done

  ___dr=$rr
  ___dg=$gg
  ___db=$bb
}


# Set the iterm2 title
set_iterm_title() {
  echo -ne "\033]0;${1}\007"
}


# Set the iterm2 background color
set_iterm_color() {
  osascript -e 'tell application "iTerm" to set background color of (current session of current terminal) to {'"$1"'}'
}


get_r $host
mr=$__
get_g $host
mg=$__
get_b $host
mb=$__
darken_rgb $mr $mg $mb
mr=$___dr
mg=$___dg
mb=$___db
get_iterm_color_string $mr $mg $mb
iterm_color_string=$__

set_iterm_color "${iterm_color_string}"
ssh ${host}
cleanup
