---
- name: 'Enable highlight hover effect for the grid view of a stack'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'mouse-over-hilite-stack'
    key_type: 'int'
    value: '1'

- name: 'Set the icon size of Dock items to 36 pixels'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'tilesize'
    key_type: 'int'
    value: '36'

- name: 'Minimize windows into their application’s icon'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'minimize-to-application'
    key_type: 'int'
    value: '1'

- name: 'Enable spring loading for all Dock items'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'enable-spring-load-actions-on-all-items'
    key_type: 'int'
    value: '1'

- name: 'Don’t animate opening applications from the Dock'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'launchanim'
    key_type: 'int'
    value: '0'
