---
- name: 'Enable highlight hover effect for the grid view of a stack'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'mouse-over-hilite-stack'
    key_type: 'int'
    value: '1'

- name: 'Set the icon size of Dock items to 36 pixels'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'tilesize'
    key_type: 'int'
    value: '36'
