---
- name: 'Enable highlight hover effect for the grid view of a stack'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'mouse-over-hilite-stack'
    key_type: 'int'
    value: '1'

# Set the icon size of Dock items to 36 pixels
- command: '/usr/bin/defaults read com.apple.dock "tilesize"'
  register: command_output
  changed_when: False
- name: 'Set the icon size of Dock items to 36 pixels'
  command: '/usr/bin/defaults write com.apple.dock "tilesize" -int 36'
  when: '"36" != command_output.stdout'
