---
- name: 'Empty Trash securely by default'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'EmptyTrashSecurely'
    key_type: 'int'
    value: '1'

- name: 'Disable the warning before emptying the Trash'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'WarnOnEmptyTrash'
    key_type: 'int'
    value: '0'

# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
- name: 'Use list view in all Finder windows by default'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'FXPreferredViewStyle'
    key_type: 'string'
    value: 'Nlsv'

- name: 'Avoid creating .DS_Store files on network volumes'
  osx_defaults:
    domain: 'com.apple.desktopservices'
    key: 'DSDontWriteNetworkStores'
    key_type: 'int'
    value: '1'

- name: 'Remove the spring loading delay for directories'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'com.apple.springing.delay'
    key_type: 'float'
    value: '0'

- name: 'Enable spring loading for directories'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'com.apple.springing.enabled'
    key_type: 'int'
    value: '1'

- name: 'Disable the warning when changing a file extension'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'FXEnableExtensionChangeWarning'
    key_type: 'int'
    value: '0'

- name: 'Display full POSIX path as Finder window title'
  osx_defaults:
    domain: 'com.apple.finder'
    key: '_FXShowPosixPathInTitle'
    key_type: 'int'
    value: '1'

- name: 'Show the finder path bar'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowPathbar'
    key_type: 'int'
    value: '1'

- name: 'Show the finder status bar'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowStatusBar'
    key_type: 'int'
    value: '1'

- name: 'Show the filename extensions'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleShowAllExtensions'
    key_type: 'int'
    value: '1'

- name: 'Disable window animations and Get Info animations'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'DisableAllAnimations'
    key_type: 'int'
    value: '1'

- name: 'Allow quitting via cmd+Q - doing so will also hide desktop icons'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'QuitMenuItem'
    key_type: 'int'
    value: '1'

- name: 'Increase the size of icons in desktop view'
  osx_plistbuddy:
    key: ":DesktopViewSettings:IconViewSettings:iconSize"
    key_type: 'float'
    value: '80.000000'
    persist_domain: 'com.apple.finder'
    plist_file: '~/Library/Preferences/com.apple.finder.plist'

- name: 'Increase the size of icons in standard view'
  osx_plistbuddy:
    key: ":StandardViewSettings:IconViewSettings:iconSize"
    key_type: 'float'
    value: '80.000000'
    persist_domain: 'com.apple.finder'
    plist_file: '~/Library/Preferences/com.apple.finder.plist'

- name: 'Show item info near icons in desktop view'
  osx_plistbuddy:
    key: ":DesktopViewSettings:IconViewSettings:showItemInfo"
    key_type: 'bool'
    value: 'true'
    persist_domain: 'com.apple.finder'
    plist_file: '~/Library/Preferences/com.apple.finder.plist'

- name: 'Show item info near icons in standard view'
  osx_plistbuddy:
    key: ":StandardViewSettings:IconViewSettings:showItemInfo"
    key_type: 'bool'
    value: 'true'
    persist_domain: 'com.apple.finder'
    plist_file: '~/Library/Preferences/com.apple.finder.plist'

- name: 'Show item info to the right of the icons on the desktop'
  osx_plistbuddy:
    key: ":DesktopViewSettings:IconViewSettings:labelOnBottom"
    key_type: 'bool'
    value: 'false'
    persist_domain: 'com.apple.finder'
    plist_file: '~/Library/Preferences/com.apple.finder.plist'

- name: 'Show icons for external hard drives on the desktop'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowExternalHardDrivesOnDesktop'
    key_type: 'int'
    value: '1'

- name: 'Show icons for hard drives on the desktop'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowHardDrivesOnDesktop'
    key_type: 'int'
    value: '1'

- name: 'Show icons for mounted servers on the desktop'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowMountedServersOnDesktop'
    key_type: 'int'
    value: '1'

- name: 'Show icons for removable media on the desktop'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowRemovableMediaOnDesktop'
    key_type: 'int'
    value: '1'
