---
- name: 'Empty Trash securely by default'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'EmptyTrashSecurely'
    key_type: 'int'
    value: '1'

- name: 'Disable the warning before emptying the Trash'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'WarnOnEmptyTrash'
    key_type: 'int'
    value: '0'

# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
- name: 'Use list view in all Finder windows by default'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'FXPreferredViewStyle'
    key_type: 'string'
    value: 'Nlsv'

- name: 'Avoid creating .DS_Store files on network volumes'
  osx_defaults:
    domain: 'com.apple.desktopservices'
    key: 'DSDontWriteNetworkStores'
    key_type: 'int'
    value: '1'

- name: 'Remove the spring loading delay for directories'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'com.apple.springing.delay'
    key_type: 'float'
    value: '0'

- name: 'Enable spring loading for directories'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'com.apple.springing.enabled'
    key_type: 'int'
    value: '1'

- name: 'Disable the warning when changing a file extension'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'FXEnableExtensionChangeWarning'
    key_type: 'int'
    value: '0'

- name: 'Display full POSIX path as Finder window title'
  osx_defaults:
    domain: 'com.apple.finder'
    key: '_FXShowPosixPathInTitle'
    key_type: 'int'
    value: '1'

- name: 'Show the finder path bar'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowPathbar'
    key_type: 'int'
    value: '1'

- name: 'Show the finder status bar'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowStatusBar'
    key_type: 'int'
    value: '1'

- name: 'Show the filename extensions'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleShowAllExtensions'
    key_type: 'int'
    value: '1'
