---
- name: 'Empty Trash securely by default'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'EmptyTrashSecurely'
    key_type: 'int'
    value: '1'

- name: 'Disable the warning before emptying the Trash'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'WarnOnEmptyTrash'
    key_type: 'int'
    value: '0'
