---
# ComputerName is the so-called "user-friendly" name for the Mac, it's what
# will show up on the Mac itself and what will be visible to others when
# connecting to it over a local network. This is also whats visible under the
# Sharing preference panel.
- name: 'Set the OSX ComputerName'
  osx_scutil:
    key: 'ComputerName'
    value: "{{ osxhostname }}"

# HostName is the name assigned to the computer as visible from the command
# line, and it's also used by local and remote networks when connecting through
# SSH and Remote Login.
- name: 'Set the OSX HostName'
  osx_scutil:
    key: 'HostName'
    value: "{{ osxhostname }}"

# LocalHostName is the name identifier used by Bonjour and visible through file
# sharing services like AirDrop
- command: '/usr/sbin/scutil --get LocalHostName'
  sudo: 'yes'
  register: localhostname_contents
  changed_when: False

- name: 'Set the OSX LocalHostName'
  command: '/usr/sbin/scutil --set LocalHostName "{{ osxhostname }}"'
  sudo: 'yes'
  when: '"{{ osxhostname }}" != localhostname_contents.stdout'
