---
- name: 'Ensure we can connect to this host'
  ping:
- include: hostname.yml
- include: audio.yml
- include: user_interface.yml
- include: dock.yml
- include: finder.yml
- include: iterm2.yml
- include: time_machine.yml
- include: screen.yml
