---
- name: 'Prevent time machine from prompting to use new hard drives as backup volumes'
  osx_defaults:
    domain: 'com.apple.TimeMachine'
    key: 'DoNotOfferNewDisksForBackup'
    key_type: 'int'
    value: '1'
    force: 'yes'
