---
- name: 'Set the highlight color to green'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleHighlightColor'
    key_type: 'string'
    value: '0.764700 0.976500 0.568600'

- name: 'Set the sidebar icon size to medium'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'NSTableViewDefaultSizeMode'
    key_type: 'int'
    value: '2'

# Always show scrollbars
# Possible values are: 'WhenScrolling', 'Automatic', and 'Always'
- command: '/usr/bin/defaults read NSGlobalDomain AppleShowScrollBars'
  register: command_output
  changed_when: False
- name: 'Always show scrollbars'
  command: '/usr/bin/defaults write NSGlobalDomain AppleShowScrollBars -string "Always"'
  when: '"Always" != command_output.stdout'
