---
- name: 'Set the highlight color to green'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleHighlightColor'
    key_type: 'string'
    value: '0.764700 0.976500 0.568600'

- name: 'Set the sidebar icon size to medium'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'NSTableViewDefaultSizeMode'
    key_type: 'int'
    value: '2'

# Possible values are: 'WhenScrolling', 'Automatic', and 'Always'
- name: 'Always show scrollbars'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleShowScrollBars'
    key_type: 'string'
    value: 'Always'
