---
- name: 'Set the highlight color to green'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleHighlightColor'
    key_type: 'string'
    value: '0.764700 0.976500 0.568600'
    force: 'yes'

- name: 'Set the sidebar icon size to medium'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'NSTableViewDefaultSizeMode'
    key_type: 'int'
    value: '2'
    force: 'yes'

# Possible values are: 'WhenScrolling', 'Automatic', and 'Always'
- name: 'Always show scrollbars'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleShowScrollBars'
    key_type: 'string'
    value: 'Always'
    force: 'yes'

- name: 'Disable auto-correct'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'NSAutomaticSpellingCorrectionEnabled'
    key_type: 'int'
    value: '0'
    force: 'yes'

- name: 'Set the locale to en_CA'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleLocale'
    key_type: 'string'
    value: 'en_CA@currency=CAD'
    force: 'yes'

- name: 'Set the measurement units to inches'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleMeasurementUnits'
    key_type: 'string'
    value: 'Inches'
    force: 'yes'

- name: 'Do not use metric units'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleMetricUnits'
    key_type: 'int'
    value: '0'
    force: 'yes'

- name: 'Set a blazingly fast keyboard repeat rate'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'KeyRepeat'
    key_type: 'int'
    value: '0'
    force: 'yes'

- name: 'Disable smart quotes'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'NSAutomaticQuoteSubstitutionEnabled'
    key_type: 'int'
    value: '0'
    force: 'yes'

- name: 'Disable smart dashes'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'NSAutomaticDashSubstitutionEnabled'
    key_type: 'int'
    value: '0'
    force: 'yes'

- name: 'Automatically quit the printer app once print jobs complete'
  osx_defaults:
    domain: 'com.apple.print.PrintingPrefs'
    key: 'Quit When Finished'
    key_type: 'int'
    value: '1'
    force: 'yes'

- name: 'Disable the "Are you sure you want to open this application?" dialog'
  osx_defaults:
    domain: 'com.apple.LaunchServices'
    key: 'LSQuarantine'
    key_type: 'int'
    value: '0'
    force: 'yes'

- name: 'Display ASCII control characters using caret notation in standard text views'
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'NSTextShowsControlCharacters'
    key_type: 'int'
    value: '1'
    force: 'yes'

- name: 'Disable the crash reporter'
  osx_defaults:
    domain: 'com.apple.CrashReporter'
    key: 'DialogType'
    key_type: 'string'
    value: 'none'
    force: 'yes'

- name: 'Check for software updates daily, not just once per week'
  osx_defaults:
    domain: 'com.apple.SoftwareUpdate'
    key: 'ScheduleFrequency'
    key_type: 'int'
    value: '1'
    force: 'yes'
