---
- name: 'Create the ~/.aliases directory'
  file:
    path: '~/.aliases'
    state: 'directory'
    mode: '0700'

- name: 'Put the ~/.aliases/git_aliases file in place'
  copy:
    src: 'git_aliases'
    dest: '~/.aliases/git_aliases'
    mode: '0600'

- shell: 'ls -1 ~/.aliases'
  register: contents
  changed_when: False

- name: 'Ensure that the .aliases directory contains nothing else'
  file:
    name: "~/.aliases/{{ item }}"
    state: 'absent'
  with_items: contents.stdout_lines
  when: item not in aliases_managed_files
